---
title: "paper"
author: ""
output: html_document
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
```

* Model description
* Why?
  - convenient interface
  - fast(?); compared to some at least
  - model flexibility (e.g., breakpoints, spatially varying trends)
  - Tweedie!
  - ?
* Simulation testing
  - against R code: unbiased parameters, coverage, predictions
  - test predictions and index against INLA, VAST, (mgcv?), ...?
  - ?
* Distinguish from VAST etc.
  - interface (inspired by glmmTMB etc.)
  - focus; simplified code base; less fully featured by design
  - speed??
  - univariate
  - breakpoints
  - compartmentalized/modular (fit, predict, newdata, index, residuals, etc.)
  - not a replacement
  - ?
* vs. INLA
  - interface
  - ML/REML vs. Bayes
  - Tweedie
  - speed??
  - anisotropy
  - added flexibility for this kind of model (spatially varying trend, breakpoints)
  - not a replacement
  - ?
* Timings against VAST, INLA, etc?
* Good demos of novel components
  - breakpoints
  - random-walk covariates
  - spatially varying trend (add generic covariates?)
  - interpolating/forecasting/stitching
  - ?
* In demos, touch on:
  - Tweedie
  - cross-validation
  - randomized quantile residuals
  - tensor splines
  - marginal effects
  - bias correction
  - barrier mesh?
  - tmbstan? likely too slow?
  - ?
