# Generated by sdmTMB:::make_enum(): do not edit by hand

.valid_family <- c(
  gaussian = 0,
  binomial = 1,
  tweedie  = 2,
  poisson  = 3,
  Gamma    = 4,
  nbinom2  = 5,
  lognormal= 6,
  student  = 7,
  Beta     = 8
)
.valid_link <- c(
  identity = 0,
  log      = 1,
  logit    = 2,
  inverse  = 3
)
