# Generated by sdmTMB:::make_enum(): do not edit by hand

.valid_family <- c(
  gaussian = 0,
  binomial = 1,
  tweedie  = 2,
  poisson  = 3,
  Gamma    = 4,
  nbinom2  = 5,
  lognormal= 6,
  student  = 7,
  Beta     = 8,
  truncated_nbinom2  = 9,
  nbinom1  = 10,
  truncated_nbinom1  = 11,
  censored_poisson  = 12,
  gamma_mix = 13,
  lognormal_mix = 14,
  nbinom2_mix = 15,
  gengamma = 16,
  betabinomial = 17
)
.valid_link <- c(
  identity = 0,
  log      = 1,
  logit    = 2,
  inverse  = 3,
  cloglog  = 4
)
